version: '3'

services: 
  api-server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on: 
      - db
    volumes: 
      - ./:/tt-api-server
    ports: 
      - 3000:3000
    environment:
      NODE_ENV: development

  db:
    image: postgres:12.1
    restart: always
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: travel-together
